-- 1) 월급/지출 (단일 row)
create table if not exists public.finance_overview (
	id integer primary key default 1 check (id = 1),
	salary bigint not null default 0,
	fixed_expense bigint not null default 0,
	variable_expense bigint not null default 0,
	updated_at timestamptz not null default timezone('utc', now())
);

insert into public.finance_overview (id)
values (1)
on conflict (id) do nothing;

-- 2) 주식 보유/모으기 상태
create table if not exists public.stock_holdings (
	id bigint generated by default as identity primary key,
	broker text not null check (broker in ('TOSS', 'SAMSUNG')),
	market text not null check (market in ('KR', 'US')),
	symbol text not null,
	name text not null,
	quote_symbol text not null,
	quantity numeric(18, 6) not null default 0,
	average_price numeric(18, 4) not null default 0,
	is_accumulating boolean not null default false,
	accumulation_started_at timestamptz,
	cadence text check (cadence in ('WEEKLY', 'MONTHLY')),
	run_day smallint check (run_day between 1 and 31),
	accumulation_type text not null check (accumulation_type in ('AMOUNT', 'SHARES')),
	accumulation_currency text not null default 'KRW' check (accumulation_currency in ('KRW', 'USD')),
	accumulation_value numeric(18, 6) not null default 0,
	created_at timestamptz not null default timezone('utc', now()),
	updated_at timestamptz not null default timezone('utc', now())
);

alter table public.stock_holdings
add column if not exists is_accumulating boolean not null default false;

alter table public.stock_holdings
add column if not exists cadence text check (cadence in ('WEEKLY', 'MONTHLY'));

alter table public.stock_holdings
add column if not exists run_day smallint check (run_day between 1 and 31);

alter table public.stock_holdings
add column if not exists accumulation_started_at timestamptz;

do $$
begin
	if not exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'stock_holdings'
			and column_name = 'accumulation_currency'
	) then
		alter table public.stock_holdings
		add column accumulation_currency text not null default 'KRW'
		check (accumulation_currency in ('KRW', 'USD'));

		update public.stock_holdings
		set accumulation_currency = case
			when market = 'US' then 'USD'
			else 'KRW'
		end;
	end if;
end;
$$;

update public.stock_holdings
set accumulation_started_at = created_at
where is_accumulating = true
	and accumulation_started_at is null;

-- 2-1) 자동 반영 로그
create table if not exists public.stock_accumulation_logs (
	id bigint generated by default as identity primary key,
	holding_id bigint not null references public.stock_holdings(id) on delete cascade,
	run_date date not null,
	local_amount numeric(18, 6) not null,
	currency text not null check (currency in ('KRW', 'USD')),
	fx_rate numeric(18, 6),
	krw_amount bigint not null,
	created_at timestamptz not null default timezone('utc', now()),
	unique (holding_id, run_date)
);

-- 3) 지출 항목
create table if not exists public.expense_items (
	id bigint generated by default as identity primary key,
	kind text not null check (kind in ('FIXED', 'VARIABLE')),
	name text not null,
	amount bigint not null default 0,
	created_at timestamptz not null default timezone('utc', now()),
	updated_at timestamptz not null default timezone('utc', now())
);

-- 4) 적금 정보
create table if not exists public.installment_savings (
	id bigint generated by default as identity primary key,
	name text not null,
	monthly_amount bigint not null default 0,
	saved_amount bigint not null default 0,
	is_recurring boolean not null default false,
	cadence text check (cadence in ('WEEKLY', 'MONTHLY')),
	run_day smallint check (run_day between 1 and 31),
	apply_mode text not null default 'TODAY' check (apply_mode in ('TODAY', 'NEXT_CYCLE')),
	recurring_started_at timestamptz,
	start_date date not null,
	maturity_date date,
	benefit_type text not null default 'INTEREST_RATE' check (benefit_type in ('INTEREST_RATE', 'MATURITY_AMOUNT')),
	benefit_value numeric(18, 3) not null default 0,
	created_at timestamptz not null default timezone('utc', now()),
	updated_at timestamptz not null default timezone('utc', now())
);

alter table public.installment_savings
add column if not exists benefit_type text not null default 'INTEREST_RATE'
check (benefit_type in ('INTEREST_RATE', 'MATURITY_AMOUNT'));

alter table public.installment_savings
add column if not exists benefit_value numeric(18, 3) not null default 0;

alter table public.installment_savings
add column if not exists saved_amount bigint not null default 0;

alter table public.installment_savings
add column if not exists is_recurring boolean not null default false;

alter table public.installment_savings
add column if not exists cadence text check (cadence in ('WEEKLY', 'MONTHLY'));

alter table public.installment_savings
add column if not exists run_day smallint check (run_day between 1 and 31);

alter table public.installment_savings
add column if not exists apply_mode text not null default 'TODAY'
check (apply_mode in ('TODAY', 'NEXT_CYCLE'));

alter table public.installment_savings
add column if not exists recurring_started_at timestamptz;

alter table public.installment_savings
alter column maturity_date drop not null;

update public.installment_savings
set is_recurring = monthly_amount > 0
where is_recurring = false
	and monthly_amount > 0;

update public.installment_savings
set cadence = 'MONTHLY'
where is_recurring = true
	and cadence is null;

update public.installment_savings
set run_day = 1
where is_recurring = true
	and run_day is null;

update public.installment_savings
set recurring_started_at = created_at
where is_recurring = true
	and recurring_started_at is null;

-- 4-1) 적금 정기 납입 자동 반영 로그
create table if not exists public.installment_contribution_logs (
	id bigint generated by default as identity primary key,
	installment_id bigint not null references public.installment_savings(id) on delete cascade,
	run_date date not null,
	amount bigint not null,
	created_at timestamptz not null default timezone('utc', now()),
	unique (installment_id, run_date)
);

-- updated_at 자동 갱신
create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
	new.updated_at = timezone('utc', now());
	return new;
end;
$$;

drop trigger if exists trg_finance_overview_updated_at on public.finance_overview;
create trigger trg_finance_overview_updated_at
before update on public.finance_overview
for each row
execute function public.touch_updated_at();

drop trigger if exists trg_stock_holdings_updated_at on public.stock_holdings;
create trigger trg_stock_holdings_updated_at
before update on public.stock_holdings
for each row
execute function public.touch_updated_at();

drop trigger if exists trg_expense_items_updated_at on public.expense_items;
create trigger trg_expense_items_updated_at
before update on public.expense_items
for each row
execute function public.touch_updated_at();

drop trigger if exists trg_installment_savings_updated_at on public.installment_savings;
create trigger trg_installment_savings_updated_at
before update on public.installment_savings
for each row
execute function public.touch_updated_at();

-- 1인 개인용 MVP: anon 공개 쓰기 허용
alter table public.finance_overview enable row level security;
alter table public.stock_holdings enable row level security;
alter table public.stock_accumulation_logs enable row level security;
alter table public.expense_items enable row level security;
alter table public.installment_savings enable row level security;
alter table public.installment_contribution_logs enable row level security;

drop policy if exists "public_all_finance_overview" on public.finance_overview;
create policy "public_all_finance_overview"
on public.finance_overview
for all
using (true)
with check (true);

drop policy if exists "public_all_stock_holdings" on public.stock_holdings;
create policy "public_all_stock_holdings"
on public.stock_holdings
for all
using (true)
with check (true);

drop policy if exists "public_all_stock_accumulation_logs" on public.stock_accumulation_logs;
create policy "public_all_stock_accumulation_logs"
on public.stock_accumulation_logs
for all
using (true)
with check (true);

drop policy if exists "public_all_expense_items" on public.expense_items;
create policy "public_all_expense_items"
on public.expense_items
for all
using (true)
with check (true);

drop policy if exists "public_all_installment_savings" on public.installment_savings;
create policy "public_all_installment_savings"
on public.installment_savings
for all
using (true)
with check (true);

drop policy if exists "public_all_installment_contribution_logs" on public.installment_contribution_logs;
create policy "public_all_installment_contribution_logs"
on public.installment_contribution_logs
for all
using (true)
with check (true);
