-- 1) 월급/지출 (단일 row)
create table if not exists public.finance_overview (
	id integer not null default 1,
	user_code text not null default 'LEGACY_OWNER',
	year_month text not null default '2026-03',
	salary bigint not null default 0,
	actual_spent bigint not null default 0,
	realized_pnl bigint not null default 0,
	memo text not null default '',
	toss_deposit_amount bigint not null default 0,
	toss_deposit_currency text not null default 'KRW' check (toss_deposit_currency in ('KRW', 'USD')),
	samsung_deposit_amount bigint not null default 0,
	samsung_deposit_currency text not null default 'KRW' check (samsung_deposit_currency in ('KRW', 'USD')),
	fixed_expense bigint not null default 0,
	variable_expense bigint not null default 0,
	updated_at timestamptz not null default timezone('utc', now())
);

alter table public.finance_overview
add column if not exists toss_deposit_amount bigint not null default 0;

alter table public.finance_overview
add column if not exists toss_deposit_currency text not null default 'KRW'
check (toss_deposit_currency in ('KRW', 'USD'));

alter table public.finance_overview
add column if not exists samsung_deposit_amount bigint not null default 0;

alter table public.finance_overview
add column if not exists samsung_deposit_currency text not null default 'KRW'
check (samsung_deposit_currency in ('KRW', 'USD'));

-- 2) 주식 보유/모으기 상태
create table if not exists public.stock_holdings (
	id bigint generated by default as identity primary key,
	user_code text not null default 'LEGACY_OWNER',
	year_month text not null default '2026-03',
	broker text not null check (
		broker in (
			'KOREA_INVEST',
			'MIRAE_ASSET',
			'NH_INVESTMENT',
			'SAMSUNG',
			'TOSS',
			'KIWOOM'
		)
	),
	market text not null check (market in ('KR', 'US')),
	symbol text not null,
	name text not null,
	quote_symbol text not null,
	quantity numeric(18, 6) not null default 0,
	average_price numeric(18, 4) not null default 0,
	is_accumulating boolean not null default false,
	accumulation_started_at timestamptz,
	cadence text check (cadence in ('WEEKLY', 'MONTHLY')),
	run_day smallint check (run_day between 1 and 31),
	accumulation_type text not null check (accumulation_type in ('AMOUNT', 'SHARES')),
	accumulation_currency text not null default 'KRW' check (accumulation_currency in ('KRW', 'USD')),
	accumulation_value numeric(18, 6) not null default 0,
	created_at timestamptz not null default timezone('utc', now()),
	updated_at timestamptz not null default timezone('utc', now())
);

alter table public.stock_holdings
add column if not exists is_accumulating boolean not null default false;

alter table public.stock_holdings
add column if not exists cadence text check (cadence in ('WEEKLY', 'MONTHLY'));

alter table public.stock_holdings
add column if not exists run_day smallint check (run_day between 1 and 31);

alter table public.stock_holdings
add column if not exists accumulation_started_at timestamptz;

alter table public.stock_holdings
drop constraint if exists stock_holdings_broker_check;

alter table public.stock_holdings
add constraint stock_holdings_broker_check
check (
	broker in (
		'KOREA_INVEST',
		'MIRAE_ASSET',
		'NH_INVESTMENT',
		'SAMSUNG',
		'TOSS',
		'KIWOOM'
	)
);

do $$
begin
	if not exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
			and table_name = 'stock_holdings'
			and column_name = 'accumulation_currency'
	) then
		alter table public.stock_holdings
		add column accumulation_currency text not null default 'KRW'
		check (accumulation_currency in ('KRW', 'USD'));

		update public.stock_holdings
		set accumulation_currency = case
			when market = 'US' then 'USD'
			else 'KRW'
		end;
	end if;
end;
$$;

update public.stock_holdings
set accumulation_started_at = created_at
where is_accumulating = true
	and accumulation_started_at is null;

-- 2-1) 자동 반영 로그
create table if not exists public.stock_accumulation_logs (
	id bigint generated by default as identity primary key,
	user_code text not null default 'LEGACY_OWNER',
	year_month text not null default '2026-03',
	holding_id bigint not null references public.stock_holdings(id) on delete cascade,
	run_date date not null,
	local_amount numeric(18, 6) not null,
	currency text not null check (currency in ('KRW', 'USD')),
	fx_rate numeric(18, 6),
	krw_amount bigint not null,
	created_at timestamptz not null default timezone('utc', now()),
	unique (holding_id, run_date, user_code, year_month)
);

-- 3) 지출 항목
create table if not exists public.expense_items (
	id bigint generated by default as identity primary key,
	user_code text not null default 'LEGACY_OWNER',
	year_month text not null default '2026-03',
	kind text not null check (kind in ('FIXED', 'VARIABLE', 'CONSUMPTION', 'INCOME')),
	name text not null,
	amount bigint not null default 0,
	created_at timestamptz not null default timezone('utc', now()),
	updated_at timestamptz not null default timezone('utc', now())
);

alter table public.expense_items
drop constraint if exists expense_items_kind_check;

alter table public.expense_items
add constraint expense_items_kind_check
check (kind in ('FIXED', 'VARIABLE', 'CONSUMPTION', 'INCOME'));

-- 4) 적금 정보
create table if not exists public.installment_savings (
	id bigint generated by default as identity primary key,
	user_code text not null default 'LEGACY_OWNER',
	year_month text not null default '2026-03',
	name text not null,
	monthly_amount bigint not null default 0,
	saved_amount bigint not null default 0,
	is_recurring boolean not null default false,
	cadence text check (cadence in ('WEEKLY', 'MONTHLY')),
	run_day smallint check (run_day between 1 and 31),
	apply_mode text not null default 'TODAY' check (apply_mode in ('TODAY', 'NEXT_CYCLE')),
	recurring_started_at timestamptz,
	start_date date not null,
	maturity_date date,
	benefit_type text not null default 'INTEREST_RATE' check (benefit_type in ('INTEREST_RATE', 'MATURITY_AMOUNT')),
	benefit_value numeric(18, 3) not null default 0,
	created_at timestamptz not null default timezone('utc', now()),
	updated_at timestamptz not null default timezone('utc', now())
);

alter table public.installment_savings
add column if not exists benefit_type text not null default 'INTEREST_RATE'
check (benefit_type in ('INTEREST_RATE', 'MATURITY_AMOUNT'));

alter table public.installment_savings
add column if not exists benefit_value numeric(18, 3) not null default 0;

alter table public.installment_savings
add column if not exists saved_amount bigint not null default 0;

alter table public.installment_savings
add column if not exists is_recurring boolean not null default false;

alter table public.installment_savings
add column if not exists cadence text check (cadence in ('WEEKLY', 'MONTHLY'));

alter table public.installment_savings
add column if not exists run_day smallint check (run_day between 1 and 31);

alter table public.installment_savings
add column if not exists apply_mode text not null default 'TODAY'
check (apply_mode in ('TODAY', 'NEXT_CYCLE'));

alter table public.installment_savings
add column if not exists recurring_started_at timestamptz;

alter table public.installment_savings
alter column maturity_date drop not null;

update public.installment_savings
set is_recurring = monthly_amount > 0
where is_recurring = false
	and monthly_amount > 0;

update public.installment_savings
set cadence = 'MONTHLY'
where is_recurring = true
	and cadence is null;

update public.installment_savings
set run_day = 1
where is_recurring = true
	and run_day is null;

update public.installment_savings
set recurring_started_at = created_at
where is_recurring = true
	and recurring_started_at is null;

-- 4-1) 적금 정기 납입 자동 반영 로그
create table if not exists public.installment_contribution_logs (
	id bigint generated by default as identity primary key,
	user_code text not null default 'LEGACY_OWNER',
	year_month text not null default '2026-03',
	installment_id bigint not null references public.installment_savings(id) on delete cascade,
	run_date date not null,
	amount bigint not null,
	created_at timestamptz not null default timezone('utc', now()),
	unique (installment_id, run_date, user_code, year_month)
);

alter table public.finance_overview
add column if not exists user_code text not null default 'LEGACY_OWNER';

alter table public.finance_overview
add column if not exists year_month text not null default '2026-03';

alter table public.finance_overview
add column if not exists actual_spent bigint not null default 0;

alter table public.finance_overview
add column if not exists realized_pnl bigint not null default 0;

alter table public.finance_overview
add column if not exists memo text not null default '';

alter table public.finance_overview
drop constraint if exists finance_overview_id_check;

alter table public.finance_overview
drop constraint if exists finance_overview_pkey;

create sequence if not exists public.finance_overview_id_seq;

-- 기존 실행 이력으로 중복된 (user_code, year_month) row가 있으면 최신 1건만 유지
with ranked_overview as (
	select
		ctid,
		row_number() over (
			partition by user_code, year_month
			order by updated_at desc, ctid desc
		) as rn
	from public.finance_overview
)
delete from public.finance_overview fo
using ranked_overview r
where fo.ctid = r.ctid
	and r.rn > 1;

-- id 중복이 있을 수 있으므로 전체 id를 재부여
with reassigned as (
	select
		ctid,
		row_number() over (order by updated_at asc, ctid asc) as new_id
	from public.finance_overview
)
update public.finance_overview fo
set id = r.new_id
from reassigned r
where fo.ctid = r.ctid;

select setval(
	'public.finance_overview_id_seq',
	coalesce((select max(id) from public.finance_overview), 0),
	true
);

alter table public.finance_overview
alter column id set default nextval('public.finance_overview_id_seq');

alter sequence public.finance_overview_id_seq
owned by public.finance_overview.id;

do $$
begin
	if not exists (
		select 1
		from pg_constraint
		where conname = 'finance_overview_pkey'
			and conrelid = 'public.finance_overview'::regclass
	) then
		alter table public.finance_overview
		add constraint finance_overview_pkey primary key (id);
	end if;
end;
$$;

drop index if exists finance_overview_user_code_key;

create unique index if not exists finance_overview_user_code_year_month_key
on public.finance_overview (user_code, year_month);

alter table public.stock_holdings
add column if not exists user_code text not null default 'LEGACY_OWNER';

alter table public.stock_accumulation_logs
add column if not exists user_code text not null default 'LEGACY_OWNER';

alter table public.stock_holdings
add column if not exists year_month text not null default '2026-03';

alter table public.stock_accumulation_logs
add column if not exists year_month text not null default '2026-03';

alter table public.stock_accumulation_logs
drop constraint if exists stock_accumulation_logs_holding_id_run_date_key;

alter table public.stock_accumulation_logs
drop constraint if exists stock_accumulation_logs_holding_id_run_date_user_code_key;

drop index if exists public.stock_accumulation_logs_holding_id_run_date_user_code_year_mont;
drop index if exists public.stock_accumulation_logs_holding_id_run_date_user_code_year_month_key;

do $$
begin
	if not exists (
		select 1
		from pg_constraint
		where conrelid = 'public.stock_accumulation_logs'::regclass
			and contype = 'u'
			and pg_get_constraintdef(oid) = 'UNIQUE (holding_id, run_date, user_code, year_month)'
	) then
		alter table public.stock_accumulation_logs
		add constraint stock_accum_logs_holding_run_user_month_key
		unique (holding_id, run_date, user_code, year_month);
	end if;
end;
$$;

alter table public.expense_items
add column if not exists user_code text not null default 'LEGACY_OWNER';

alter table public.expense_items
add column if not exists year_month text not null default '2026-03';

alter table public.installment_savings
add column if not exists user_code text not null default 'LEGACY_OWNER';

alter table public.installment_contribution_logs
add column if not exists user_code text not null default 'LEGACY_OWNER';

alter table public.installment_savings
add column if not exists year_month text not null default '2026-03';

alter table public.installment_contribution_logs
add column if not exists year_month text not null default '2026-03';

alter table public.installment_contribution_logs
drop constraint if exists installment_contribution_logs_installment_id_run_date_key;

alter table public.installment_contribution_logs
drop constraint if exists installment_contribution_logs_installment_id_run_date_user_code_key;

drop index if exists public.installment_contribution_logs_installment_id_run_date_user_code_ye;
drop index if exists public.installment_contribution_logs_installment_id_run_date_user_code_year_month_key;

do $$
begin
	if not exists (
		select 1
		from pg_constraint
		where conrelid = 'public.installment_contribution_logs'::regclass
			and contype = 'u'
			and pg_get_constraintdef(oid) = 'UNIQUE (installment_id, run_date, user_code, year_month)'
	) then
		alter table public.installment_contribution_logs
		add constraint install_contrib_install_run_user_month_key
		unique (installment_id, run_date, user_code, year_month);
	end if;
end;
$$;

update public.finance_overview
set user_code = 'LEGACY_OWNER'
where user_code is null;

update public.finance_overview
set year_month = '2026-03'
where year_month is null;

update public.finance_overview
set realized_pnl = 0
where realized_pnl is null;

update public.stock_holdings
set user_code = 'LEGACY_OWNER'
where user_code is null;

update public.stock_holdings
set year_month = '2026-03'
where year_month is null;

update public.stock_accumulation_logs sal
set user_code = coalesce(sh.user_code, 'LEGACY_OWNER'),
	year_month = coalesce(sh.year_month, '2026-03')
from public.stock_holdings sh
where sal.holding_id = sh.id
	and (sal.user_code is null or sal.user_code = 'LEGACY_OWNER');

update public.expense_items
set user_code = 'LEGACY_OWNER'
where user_code is null;

update public.expense_items
set year_month = '2026-03'
where year_month is null;

update public.installment_savings
set user_code = 'LEGACY_OWNER'
where user_code is null;

update public.installment_savings
set year_month = '2026-03'
where year_month is null;

update public.installment_contribution_logs icl
set user_code = coalesce(isv.user_code, 'LEGACY_OWNER'),
	year_month = coalesce(isv.year_month, '2026-03')
from public.installment_savings isv
where icl.installment_id = isv.id
	and (icl.user_code is null or icl.user_code = 'LEGACY_OWNER');

-- updated_at 자동 갱신
create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
	new.updated_at = timezone('utc', now());
	return new;
end;
$$;

drop trigger if exists trg_finance_overview_updated_at on public.finance_overview;
create trigger trg_finance_overview_updated_at
before update on public.finance_overview
for each row
execute function public.touch_updated_at();

drop trigger if exists trg_stock_holdings_updated_at on public.stock_holdings;
create trigger trg_stock_holdings_updated_at
before update on public.stock_holdings
for each row
execute function public.touch_updated_at();

drop trigger if exists trg_expense_items_updated_at on public.expense_items;
create trigger trg_expense_items_updated_at
before update on public.expense_items
for each row
execute function public.touch_updated_at();

drop trigger if exists trg_installment_savings_updated_at on public.installment_savings;
create trigger trg_installment_savings_updated_at
before update on public.installment_savings
for each row
execute function public.touch_updated_at();

create or replace function public.claim_legacy_data()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
	current_user_key text := auth.uid()::text;
	legacy_count bigint := 0;
	other_owner_count bigint := 0;
	own_count bigint := 0;
	migrated boolean := false;
begin
	if auth.uid() is null then
		raise exception '로그인이 필요합니다.';
	end if;

	select count(*)
	into own_count
	from public.finance_overview
	where user_code = current_user_key;

	if own_count > 0 then
		return jsonb_build_object('migrated', false);
	end if;

	select count(*)
	into other_owner_count
	from public.finance_overview
	where user_code <> 'LEGACY_OWNER';

	select count(*)
	into legacy_count
	from public.finance_overview
	where user_code = 'LEGACY_OWNER';

	if legacy_count > 0 and other_owner_count = 0 then
		update public.finance_overview
		set user_code = current_user_key
		where user_code = 'LEGACY_OWNER';

		update public.expense_items
		set user_code = current_user_key
		where user_code = 'LEGACY_OWNER';

		update public.stock_holdings
		set user_code = current_user_key
		where user_code = 'LEGACY_OWNER';

		update public.stock_accumulation_logs
		set user_code = current_user_key
		where user_code = 'LEGACY_OWNER';

		update public.installment_savings
		set user_code = current_user_key
		where user_code = 'LEGACY_OWNER';

		update public.installment_contribution_logs
		set user_code = current_user_key
		where user_code = 'LEGACY_OWNER';

		migrated := true;
	end if;

	return jsonb_build_object('migrated', migrated);
end;
$$;

revoke all on function public.claim_legacy_data() from public;
grant execute on function public.claim_legacy_data() to authenticated;

-- Kakao 로그인 사용자 본인 데이터만 조회/수정 허용
alter table public.finance_overview enable row level security;
alter table public.stock_holdings enable row level security;
alter table public.stock_accumulation_logs enable row level security;
alter table public.expense_items enable row level security;
alter table public.installment_savings enable row level security;
alter table public.installment_contribution_logs enable row level security;

drop policy if exists "public_all_finance_overview" on public.finance_overview;
drop policy if exists "auth_own_finance_overview" on public.finance_overview;
create policy "auth_own_finance_overview"
on public.finance_overview
for all
to authenticated
using (auth.uid()::text = user_code)
with check (auth.uid()::text = user_code);

drop policy if exists "public_all_stock_holdings" on public.stock_holdings;
drop policy if exists "auth_own_stock_holdings" on public.stock_holdings;
create policy "auth_own_stock_holdings"
on public.stock_holdings
for all
to authenticated
using (auth.uid()::text = user_code)
with check (auth.uid()::text = user_code);

drop policy if exists "public_all_stock_accumulation_logs" on public.stock_accumulation_logs;
drop policy if exists "auth_own_stock_accumulation_logs" on public.stock_accumulation_logs;
create policy "auth_own_stock_accumulation_logs"
on public.stock_accumulation_logs
for all
to authenticated
using (auth.uid()::text = user_code)
with check (auth.uid()::text = user_code);

drop policy if exists "public_all_expense_items" on public.expense_items;
drop policy if exists "auth_own_expense_items" on public.expense_items;
create policy "auth_own_expense_items"
on public.expense_items
for all
to authenticated
using (auth.uid()::text = user_code)
with check (auth.uid()::text = user_code);

drop policy if exists "public_all_installment_savings" on public.installment_savings;
drop policy if exists "auth_own_installment_savings" on public.installment_savings;
create policy "auth_own_installment_savings"
on public.installment_savings
for all
to authenticated
using (auth.uid()::text = user_code)
with check (auth.uid()::text = user_code);

drop policy if exists "public_all_installment_contribution_logs" on public.installment_contribution_logs;
drop policy if exists "auth_own_installment_contribution_logs" on public.installment_contribution_logs;
create policy "auth_own_installment_contribution_logs"
on public.installment_contribution_logs
for all
to authenticated
using (auth.uid()::text = user_code)
with check (auth.uid()::text = user_code);
